In [1]:
import torch

In [2]:
# 유용한 함수들에 대해서 알아볼게요.

In [3]:
# 먼저 expand 함수입니다.
# expand 함수는 차원의 크기가 1인 차원을 원하는 크기로 늘려주는 역할을 합니다.
x = torch.FloatTensor([[[1, 2]],
                       [[3, 4]]])
x.size()

torch.Size([2, 1, 2])

In [4]:
# 이렇게 사용해주면 같은 데이터를 반복하여 리스트에 넣습니다.
y = x.expand(2, 3, 2)
print(y)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


In [5]:
# 랜덤 수열을 생성하는 함수도 있습니다.
x = torch.randperm(10)
x

tensor([1, 9, 2, 8, 6, 3, 7, 4, 0, 5])

In [9]:
# argmax는 가장 큰 값의 인덱스를 반환합니다.
y.argmax(dim=-1)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [11]:
# argmax의 상위버전인 topk 함수도 있는데, argmax가 가장 큰 한개의 값의 인덱스를 반환하는 것이었다면
# topk 함수는 가장 큰 k개의 값과 인덱스를 모두 반환합니다.
y.topk(k=1, dim=-1)

torch.return_types.topk(
values=tensor([[[2.],
         [2.],
         [2.]],

        [[4.],
         [4.],
         [4.]]]),
indices=tensor([[[1],
         [1],
         [1]],

        [[1],
         [1],
         [1]]]))

In [15]:
# 정렬을 할 수 있습니다.
values, indexes = x.sort()
values

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# 특정 조건에 맞는 값들을 골라낼 수 있습니다.
x = torch.FloatTensor([[1, 2, 3, 4, 5],
                       [6, 7, 8, 9, 10]])
mask = x > 5
mask

tensor([[False, False, False, False, False],
        [ True,  True,  True,  True,  True]])

In [17]:
# 5보다 크면, -1로 나머지는 그대로 둡니다.
x.masked_fill(mask, -1)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [-1., -1., -1., -1., -1.]])

In [18]:
# 딥러닝을 진행하다보면, 0과 1 배열이 필요할 때가 있는데 그럴 때 ones와 zeros를 사용합니다.
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [19]:
# x의 크기와 같은 값을 반환할 수 있습니다.
torch.ones_like(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])