In [2]:
import torch

In [3]:
# 먼저 텐서를 생성하죠
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
x.shape

torch.Size([2, 2])

In [6]:
# 이렇게 인덱싱을 할 수 있습니다.
# 첫번째 행
x[0]

tensor([1., 2.])

In [7]:
# 첫번째 열
x[:, 0]

tensor([1., 3.])

In [9]:
# 가장 뒤에 있는 값
x[-1]

tensor([3., 4.])

In [11]:
# 직접 인덱싱
x[1, 1]

tensor(4.)

In [15]:
# split 함수를 통해 차원의 크기가 4가 되도록 쪼개는 겁니다.
# 마지막의 경우 데이터가 2개밖에 안남으니, 그냥 2개만 적었군요.
x = torch.FloatTensor(10, 4)
splits = x.split(4)
for split in splits:
  print(split.shape)

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [18]:
# 반대로 chunk함수는 크기에 상관없이 원하는 개수로 나누는 겁니다.
# 크기 상관없이 3등분 하는거죠
x = torch.FloatTensor(8, 4)
chunks = x.chunk(3)
for chunk in chunks:
  print(chunk.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


In [19]:
# index_select 함수를 통해서 원하는 인덱스만 추출할 수 있습니다.
x = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
print(x)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [24]:
indices = torch.LongTensor([2, 0])
x.index_select(dim=0, index=indices)

tensor([[5., 6.],
        [1., 2.]])

In [25]:
# 지금부터는 여러 텐서를 합쳐서 하나의 텐서로 만드는 방법을 알아봅시다.
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])

In [28]:
# dim의 값을 0으로 설정하면 세로로 데이터를 붙입니다.
torch.concat([x, y], dim=0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

In [29]:
# dim의 값을 1로 설정하면 가로로 데이터를 붙입니다.
torch.concat([x, y], dim=1)

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])

In [30]:
# 이번에는 stack에 대해서 알아봅시다.
z = torch.stack([x, y])
print(z)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])


In [31]:
# stack을 사용하면 맨 앞에 새로운 차원이 생깁니다.
z.shape

torch.Size([2, 3, 3])