In [5]:
import torch

In [6]:
# 실수형 텐서를 선언
ft = torch.FloatTensor([[1,2], [3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [7]:
# 임의의 값으로 채워진 원하는 크기의 텐서를 만들고자 한다면
x = torch.FloatTensor(3, 4)
x

tensor([[-1.4881e-15,  3.1755e-41, -9.9005e-16,  3.1755e-41],
        [ 7.0062e+22,  2.1715e-18,  4.5447e+30,  7.0062e+22],
        [ 2.1707e-18,  1.9284e+31,  3.2314e-18,  3.7748e-08]])

In [8]:
import numpy as np

In [12]:
# 파이토치는 넘파이와 높은 호환성을 자랑합니다.
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [13]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [14]:
# 반대로 넘파이로 돌아갈 수도 있습니다.
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [15]:
# 텐서는 타입 변환도 간단합니다.
ft.long()

tensor([[1, 2],
        [3, 4]])

In [17]:
ft.float()

tensor([[1., 2.],
        [3., 4.]])

In [18]:
# 텐서의 크기를 구할 수 있습니다.
x = torch.FloatTensor([[1,2], [3,4]])
print(x.size())
print(x.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [19]:
# 텐서의 차원수를 알기 위해서는 dim을 사용합니다.
x.dim()

2