In [1]:
import torch

In [2]:
# 먼저 텐서를 만들어볼게요.
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[1, 2],
                        [3, 4]]])
x.shape

torch.Size([2, 2, 2])

In [3]:
# view 함수는 원하는 형태로 형태변환을 할 수 있습니다.
x.view(8)

tensor([1., 2., 3., 4., 1., 2., 3., 4.])

In [5]:
x.view(2, 4)

tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.]])

In [6]:
# -1을 이용하면 인자를 넣어주지 않아도 자동으로 해당 값에 맞게 할당합니다.
x.view(4, -1)

tensor([[1., 2.],
        [3., 4.],
        [1., 2.],
        [3., 4.]])

In [9]:
# 먼저 1, 2, 2 형태의 텐서를 선언해볼게요.
x = torch.FloatTensor([[[1, 2]],
                       [[3, 4]]])
x.shape

torch.Size([2, 1, 2])

In [12]:
# squeeze 함수는 차원의 크기가 1인 값을 줄여줍니다.
x.squeeze().shape

torch.Size([2, 2])

In [14]:
# 차원 인덱스를 지정할 수 있는데 크기가 1이 아닌 경우 텐서가 반환됩니다.
x.squeeze(0).shape

torch.Size([2, 1, 2])

In [15]:
# 이번에는 unsqueeze 함수입니다.
# unsqueeze함수는 차원에 1을 생성합니다.
x = torch.FloatTensor([1, 2])
x.shape

torch.Size([2])

In [17]:
x.unsqueeze(0).shape

torch.Size([1, 2])