In [9]:
import torch

In [10]:
# a는 2차원 배열이고, 1, 2, 3, 4로 구성되어있고, b도 2차원 배열로 10, 11, 12, 13으로 구성되어있다고 합시다.
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[10, 11],
                       [12, 13]])

In [11]:
# 두 행렬의 덧셈을 사용해볼까요?
a+b

tensor([[11., 13.],
        [15., 17.]])

In [12]:
# 뺄셈, 곱셈, 나눗셈도 동일한 방식으로 진행됩니다.
print(a-b)
print(a*b)
print(a/b)

tensor([[-9., -9.],
        [-9., -9.]])
tensor([[10., 22.],
        [36., 52.]])
tensor([[0.1000, 0.1818],
        [0.2500, 0.3077]])


In [13]:
# 제곱도 비슷하게 취해볼 수 있습니다.
a**b

tensor([[1.0000e+00, 2.0480e+03],
        [5.3144e+05, 6.7109e+07]])

In [14]:
# 논리 연산자도 마찬가지로 쉽게 구할 수 있습니다.
a==b

tensor([[False, False],
        [False, False]])

In [15]:
# 인플레이스 연산이라는 것이 있습니다.
# 원래의 경우 a.mul()의 값을 계산하면 새로운 공간에 값을 할당하는데, 인플레이스 연산을 적용하면 a의 값이 바뀌게 됩니다.
print(a.add_(b))
print(a)

tensor([[11., 13.],
        [15., 17.]])
tensor([[11., 13.],
        [15., 17.]])


In [16]:
# 얼핏 보면 새로운 메모리의 공간을 할당하는 작업이 생략되기 때문에 속도나, 공간 사용 측면에서 효율적일 것 같지만, 파이토치 측은 가비지 컬렉터가
# 효율적으로 작동하기 때문에 굳이 인플레이스 연산을 사용할 필요가 없습니다.

In [20]:
# 다음 행렬이 이싿고 합시다.
x = torch.FloatTensor([[1, 2], [3, 4]])

In [21]:
# sum 함수를 사용해 전체 행렬을 더할 수 있고,
x.sum()

tensor(10.)

In [22]:
# mean을 이용해서 평균을 구할 수 있습니다.
x.mean()

tensor(2.5000)

In [26]:
# dim의 값이 0이면 열에 대하여 합산을 진행하고
print(x.sum(dim=0))
# dim의 값이 1이면 행의 값에 대하여 합산을 진행합니다.
print(x.sum(dim=1))

tensor([4., 6.])
tensor([3., 7.])


In [27]:
# 지금까지는 텐서의 크기가 같은 경우에 대해서 예를 들었습니다.
# 이번에는 텐서+스칼라의 형태를 보시죠.
x = torch.FloatTensor([[1, 2], [3, 4]])
y = 1
print(x+y)

tensor([[2., 3.],
        [4., 5.]])


In [28]:
# 텐서+벡터의 경우는 비어있는 부분에 숫자를 추가해서 양쪽을 똑같이 밪추어줍니다.
x = torch.FloatTensor([[1, 2], [4, 8]])
y = torch.FloatTensor([3, 5])
print(x+y)

tensor([[ 4.,  7.],
        [ 7., 13.]])


In [29]:
# 텐서+텐서의 경우 위의 경우와 동일하게 진행됩니다.
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3], [5]])
print(x+y)

tensor([[4., 5.],
        [6., 7.]])
